config/routes.rb
SecondhandUstc::Application.routes.draw do

  root 'products#index'

    resources :products do
      member do
      end
  
      collection do
        get 'search_by_title_keyword'
        get 'sell'
        get 'buy'
        get 'evaluate'
        get 'newest'
      end
    end
    resources :comments

  

end

app/models/comment.rb
class Comment
  include Mongoid::Document
  belongs_to :product
 
  field :content
  field :flag


end

app/models/product.rb
class Product
  include Mongoid::Document
  include Mongoid::Timestamps

  belongs_to :onwer, class_name: 'User'
  has_many :comments

  field :price, type: Integer
  field :tag
  field :picture, type: Array
  field :title
  field :description
  field :url
  field :en_tag

  before_save :mark_tag

  def mark_tag #将汉字标记转化为英文标记，用于样式
    if self.tag == '出售'
      self.en_tag = 'sell'
    elsif self.tag == '求购'
      self.en_tag = 'buy'
    else
      self.en_tag = 'evaluate'
    end
  end
end

app/models/user.rb
class User
  include Mongoid::Document
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.product_id = params[:product_id]
    respond_to do |format|
      if @comment.save
        flash[:notice] = "评论成功"
        format.js 
      end
    end
  end

  def comment_params
    params.require(:comment).permit(:content, :flag)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all.desc(:created_at).page params[:page]
  end

  def new
    @product = Product.new
  end

  def edit
    @product = Product.find(params[:id])
  end

  def update
    @product = Product.find(params[:id])
    @product.update_attributes(product_params)
    redirect_to product_url(@product)
  end

  def create
    @product = Product.new(product_params)
    @product.picture = [] 
    params[:product][:picture].each do |key,value|
      @product.picture << value
    end
    if @product.save
      flash[:notice] = "创建成功"
      redirect_to product_url(@product)
    else
      render 'new'
    end
  end


  def show
    @product = Product.includes(:comments).find(params[:id])
  end
  
  def search_by_title_keyword
    @products = Product.where(:title => /#{params[:keyword]}/).page params[:page]
    render 'index'
  end
  
  def sell
    @products = Product.where(:tag => '出售').desc(:created_at).page params[:page]
    session[:current_tag] = '出售'
    render 'index'
  end

  def evaluate
    @products = Product.where(tag: '估价').desc(:created_at).page params[:page]
    session[:current_tag] = '估价'
    render 'index'
  end

  def buy
    @products = Product.where(tag: '求购').desc(:created_at).page params[:page]
    session[:current_tag] = '求购'
    render 'index'
  end

  # ['sell','evaluate','buy'].each do |tag|
  #   define_method(tag) do
  #     @products = Product.where(tag: "#{tag}").page params[:page]
  #     session[:current_tag] = tag
  #     render 'index'
  #   end
  # end
  def product_params
    params.require(:product).permit(:title, :url, :tag, :picture, :description)
  end

  def newest
    @products = Product.desc(:created_at).limit(20)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
  def format_date(time)
    "#{time.year}年#{time.month}月#{time.day}日"
  end

  def more_than_one_picture?(pic)
    pic.length > 1 ? true : false
  end

  def how_many_pictures(pic)
    pic.length
  end

  def tag_chn_to_en(tag)
    if tag == '出售'
      return 'sell'
    elsif tag == '求购'
      return 'buy'
    else
      'evaluate'
    end
  end
      
end

app/views/comments/_comment.html.erb
  <li class="media bottom-border">
    <a class="pull-left" href="#">
      <%= image_tag "brand.png", class: 'media-object' %>
    </a>
    <div class="media-body">
      <h4 class="media-heading">FROM USTC</h4>
      <%= sanitize(comment.content) %>
    </div>
  </li>

app/views/comments/create.js.erb
$('#comment-content').val('');
$('#new_reply').before("<div class='alert alert-dismissable alert-success'><button type='button' class='close' data-dismiss='alert' aria-hidden='true'>X</button><%= flash[:notice] %></div>");
$('#reply-list').append('<%= j(render partial: "comments/comment", object: @comment, as: :comment) %>');

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default" role="navigation">
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
      <span class="sr-only">Toggle navigation</span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">
      <%= image_tag('brand.png') %>
      跳蚤市场
    </a>
  </div>

  <!-- Collect the nav links, forms, and other content for toggling -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav">
      <li><%= link_to '发布', new_product_path %></li>
      <li><%= link_to '最新', newest_products_path %></li>
      <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">
          <%= session[:current_tag] || "类别" %> <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><%= link_to '出售', sell_products_path %></li>
          <li><%= link_to '估价', evaluate_products_path %></li>
          <li><%= link_to '求购', buy_products_path %></li>
        </ul>
      </li>
    </ul>
    
    <%= render 'products/search_form' %>
    
    <ul class="nav navbar-nav navbar-right">
      <li><a href="https://github.com/loveltyoic/Secondhand-USTC">关于这个网站</a></li>      
      <!-- <li class="dropdown">
        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>
        <ul class="dropdown-menu">
          <li><a href="#">Action</a></li>
          <li><a href="#">Another action</a></li>
          <li><a href="#">Something else here</a></li>
          <li><a href="#">Separated link</a></li>
        </ul>
      </li> -->
    </ul>
  </div><!-- /.navbar-collapse -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>SecondhandUstc</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application"  %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/nav' %>
<div class="container">
<%= yield %>
</div>
</body>
</html>

app/views/products/_new_product_form.html.erb
<%= simple_form_for @product do |f| %>
  <%= f.input :title, label: '标题' %>
  <%= f.input :tag, label: '标签', collection: ['出售', '求购', '估价'] %>
  <div id="pic-url">
    <div class="form-group">
      <label class="control-label col-lg-2">图片地址</label>
      <div class="col-lg-10">
        <input name=product[picture][0] class="form-control" type='text'></input>
      </div>
    </div>
  </div>
  <a id="add_pic" href="#">增加图片</a>
  <%= f.input :description, as: :text, label: '描述' %>
  <%= f.input :url %>
  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <button type="submit" class="btn btn-primary">发布</button>
    </div>
  </div>
<% end %>
<script>
var count=1;
$('#add_pic').click(function(){
  $('#pic-url').append('<div class="form-group"><div class="col-lg-offset-2 col-lg-10"><input name=product[picture]['+(count++)+'] type="text" class="form-control"></input></div></div>');
});
</script>

app/views/products/_picture_slide.html.erb
<% unless more_than_one_picture?(@product.picture) %> 
  <!-- 只有一张图片，不用幻灯片 -->
  <%= image_tag @product.picture[0] %>
<% else %>
<div id="product-picture" class="carousel slide">
  <!-- 多于一张图片，用幻灯片播放 -->
  <div class="carousel-inner">
    <% @product.picture.each do |pic| %>
      <div class="item picture-box">
        <%= image_tag pic %>
        <div class="carousel-caption">
        </div>
      </div>
    <% end %>
  </div>

  <!-- Controls -->
<!--     <a class="carousel-control" href="#product-picture" data-slide="prev">
    <span class="icon-prev"></span>
  </a>
  <a class="right carousel-control" href="#product-picture" data-slide="next">
    <span class="icon-next"></span>
  </a> -->
</div>
<!-- 用图片缩略图作为选择器 -->
<div class="row product-thumb">
  <% @product.picture.each_index do |index| %>
  <div class="col-md-2">
    <div class="thumbnail">
      <%= image_tag @product.picture[index], "data-target" => "#product-picture", "data-slide-to" => "#{index}" %>
    </div>
  </div>
  <% end %>
</div>
<% end %>
<script>
$('div.carousel-inner .item:first').addClass("active");
$('#product-picture').carousel();
</script>

app/views/products/_product.html.erb
<div class="box col-md-5">
  <div class="ribbon">
    <span class="<%= product.en_tag %>"><%= product.tag %></span>
  </div>
  <%= link_to (image_tag product.picture[0]), product %>
  <h4 data-toggle="tooltip" title="<%= product.title %>"><%= truncate product.title %></h4>
</div>

app/views/products/_reply_box.html.erb
<div class="comments">
  <h4><span class='glyphicon glyphicon-comment' style="padding:5px"></span></h4>
  <ul id="reply-list" class="meida-list">
    <% unless @product.comments.empty? %>    
    <%= render partial: 'comments/comment', collection: @product.comments, as: :comment %>
    <% end %>
  </ul>
  <div class="bottom-border" id="new_reply">
    <%= form_for Comment.new, :url => comments_path(product_id: @product.id), :remote => true, "data-type" => 'script' do |f| %>
      <%= f.text_area :content, placeholder: '输入评论内容', id: 'comment-content', :class => "col-md-12 well", :rows => "4" %>
      <div class="submit_buttons">
        <button type="submit" id="btn_reply" class="btn btn-primary">提交评论</button>
      </div>
    <% end %>  
  </div>
</div>

app/views/products/_search_form.html.erb
<%= form_tag search_by_title_keyword_products_path, :class => 'navbar-form navbar-left', method: 'get' do %>
  <div class="form-group">
    <%= text_field_tag :keyword, params[:keyword], class: "form-control", :placeholder => "关键字" %>
  </div>
  <button type="submit" name="nil" class="btn"><span class="glyphicon glyphicon-search"></span></button>
<% end %>

app/views/products/edit.html.erb
<div class="row">
  <div class="col-md-7">
    <%= render 'new_product_form' %>
  </div>
</div>

app/views/products/index.html.erb
<div id="masonry-container" class="transitions-enabled centered infinite-scroll clearfix">
  <div class="page">
    <%= render @products %>
  </div>
</div>
<%= paginate @products %>
<div id="gotop"></div>
<style type="text/css">
#gotop {
    display:none;
    width:55px;
    height:55px;
    position:fixed;
    right:25px;
    bottom:25px;
    background: url("<%= asset_path('backtop.png') %>") no-repeat -70px 0px;    
}
</style>
<script>
$(document).ready(function(){
  $("#masonry-container").infinitescroll({
    navSelector : "nav.pagination", // selector for the paged navigation (it will be hidden)
    nextSelector : "nav.pagination a[rel=next]", // selector for the NEXT link (to page 2)
    itemSelector : "#masonry-container div.box",
    loading: {
        finishedMsg: '没有更多结果了.',
        img: 'http://i.imgur.com/6RMhx.gif',
        msgText: '正在加载下一页'
      }
    },
    function( newElements ) {
      // hide new items while they are loading
      var $newElems = $( newElements ).css({ opacity: 0 });
      // ensure that images load before adding to masonry layout
      $newElems.imagesLoaded(function(){
        // show elems now they're ready
        $newElems.animate({ opacity: 1 });
        $("#masonry-container").masonry( 'appended', $newElems, true ); 
      });
    }); // selector for all items you'll retrieve
    $(window).load(function(){
      $('#masonry-container').masonry({
        itemSelector: '.box',
        // columnWidth: 150,
        // 一共有6个column,每个column的width可以是固定值，也可以相对容器的宽度设定
        columnWidth: function( containerWidth ) {
          console.log(containerWidth);
          return containerWidth / 6;
        },
        // gutterWidth: 10,
        //isAnimated: !Modernizr.csstransitions,
        // isRTL: true //从右至左排列
        isFitWidth: true //居中排列
      });
    });
    // $('#masonry-container').isotope({
    //   // options
    //   itemSelector : '.box',
    //   layoutMode : 'fitRows'
    // });
    function goTop()
    {
      $(window).scroll(function(e) {
          //若滚动条离顶部大于100元素
          if($(window).scrollTop()>100)
              $("#gotop").fadeIn(1000);//以1秒的间隔渐显id=gotop的元素
          else
              $("#gotop").fadeOut(1000);//以1秒的间隔渐隐id=gotop的元素
      });
    };

    $("#gotop").click(function(e) {
      //以0.5秒的间隔返回顶部
      $('body,html').animate({scrollTop:0},500);
    });
    $("#gotop").mouseover(function(e) {
        $(this).css("background","url(<%= asset_path('backtop.png') %>) no-repeat 0px 0px");
    });
    $("#gotop").mouseout(function(e) {
        $(this).css("background","url(<%= asset_path('backtop.png') %>) no-repeat -70px 0px");
    });
    goTop();//实现回到顶部元素的渐显与渐隐
    $("div.box h4").tooltip({placement: 'bottom'});
});
</script>

app/views/products/new.html.erb
<div class="row">
  <div class="col-md-7">
    <%= render 'new_product_form' %>
  </div>
</div>

app/views/products/newest.html.erb
<div id="masonry-container" class="transitions-enabled centered infinite-scroll clearfix">
  <div class="page">
    <%= render @products %>
  </div>
</div>

app/views/products/show.html.erb
<div class="thing_wrapper row">
  <div class="row">
    <div class="col-md-12 thing_header">
      <h1><%= @product.title %></h1>
      <h4><%= format_date(@product.created_at) %></h4>
    </div>
  </div>
  <div class="row">
    <div class="col-md-7 bottom-border right-border">
      <div class="bottom-border">
        <%= render 'picture_slide' %>
      </div>
      <div class="bottom-border">
        <h4><%= simple_format(@product.description) %><h4>
      </div>
      <h4><a href='<%= @product.url %>'>BBS连接</a></h4>
      <%= render 'reply_box' %>
    </div>
    <div class="col-md-4">
    </div>
  </div>
</div>